---

- name: "UFW | Rule | Processing rule '{{ rule.key }}'"
  community.general.ufw:
    rule: "{{ rule.value.rule | default(defaults_rule.rule) }}"
    proto: "{{ rule.value.proto | default(defaults_rule.proto) }}"
    log: "{{ rule.value.log | default(defaults_rule.log) }}"
    from_ip: "{{ rule.value.from_ip | default(defaults_rule.from_ip) }}"
    to_ip: "{{ rule.value.to_ip | default(defaults_rule.to_ip) }}"
    comment: "{{ rule.value.comment | default(defaults_rule.comment + rule.key) }}"
    direction: "{{ rule.value.direction | default(defaults_rule.direction) }}"
    port: "{{ rule.value.port }}"
    delete: "{{ delete_rule }}"
  notify: Reload-UFW
  when:
    - rule.value.port is defined
    - rule.value.insert is undefined

- name: "UFW | Rule | Processing rule - (w/o port restriction) - '{{ rule.key }}'"
  community.general.ufw:
    rule: "{{ rule.value.rule | default(defaults_rule.rule) }}"
    proto: "{{ rule.value.proto | default(defaults_rule.proto) }}"
    log: "{{ rule.value.log | default(defaults_rule.log) }}"
    from_ip: "{{ rule.value.from_ip | default(defaults_rule.from_ip) }}"
    to_ip: "{{ rule.value.to_ip | default(defaults_rule.to_ip) }}"
    comment: "{{ rule.value.comment | default(defaults_rule.comment + rule.key) }}"
    direction: "{{ rule.value.direction | default(defaults_rule.direction) }}"
    delete: "{{ delete_rule }}"
  notify: Reload-UFW
  when:
    - rule.value.port is undefined
    - rule.value.insert is undefined

- name: "UFW | Rule | Processing rule - (at custom position) - '{{ rule.key }}'"
  community.general.ufw:
    rule: "{{ rule.value.rule | default(defaults_rule.rule) }}"
    proto: "{{ rule.value.proto | default(defaults_rule.proto) }}"
    log: "{{ rule.value.log | default(defaults_rule.log) }}"
    from_ip: "{{ rule.value.from_ip | default(defaults_rule.from_ip) }}"
    to_ip: "{{ rule.value.to_ip | default(defaults_rule.to_ip) }}"
    comment: "{{ rule.value.comment | default(defaults_rule.comment + rule.key) }}"
    direction: "{{ rule.value.direction | default(defaults_rule.direction) }}"
    insert: "{{ rule.value.insert | default(rule.value.position) }}"
    port: "{{ rule.value.port }}"
    delete: "{{ delete_rule }}"
  notify: Reload-UFW
  when:
    - rule.value.port is defined
    - rule.value.insert is defined or rule.value.position is defined

- name: "UFW | Rule | Processing rule - (w/o port restriction at custom position) - '{{ rule.key }}'"
  community.general.ufw:
    rule: "{{ rule.value.rule | default(defaults_rule.rule) }}"
    proto: "{{ rule.value.proto | default(defaults_rule.proto) }}"
    log: "{{ rule.value.log | default(defaults_rule.log) }}"
    from_ip: "{{ rule.value.from_ip | default(defaults_rule.from_ip) }}"
    to_ip: "{{ rule.value.to_ip | default(defaults_rule.to_ip) }}"
    comment: "{{ rule.value.comment | default(defaults_rule.comment + rule.key) }}"
    direction: "{{ rule.value.direction | default(defaults_rule.direction) }}"
    insert: "{{ rule.value.insert | default(rule.value.position) }}"
    delete: "{{ delete_rule }}"
  notify: Reload-UFW
  when:
    - rule.value.port is undefined
    - rule.value.insert is defined or rule.value.position is defined
